# MPLAB IDE generated this makefile for use with GNU make.
# Project: DetectorColor.mcp
# Date: Sun Mar 10 20:08:16 2019

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

PruebaMultiply.cof : PruebaMultiply.o
	$(CC) /p16F887 "PruebaMultiply.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"PruebaMultiply.cof" /M"PruebaMultiply.map" /W /x

PruebaMultiply.o : PruebaMultiply.asm ../../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/p16f887.inc
	$(AS) /q /p16F887 "PruebaMultiply.asm" /l"PruebaMultiply.lst" /e"PruebaMultiply.err" /d__DEBUG=1

clean : 
	$(CC) "PruebaMultiply.o" "PruebaMultiply.hex" "PruebaMultiply.err" "PruebaMultiply.lst" "PruebaMultiply.cof"

