		PROCESSOR P16F887
		INCLUDE <P16F887.INC>
		__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
		__CONFIG _CONFIG2, (_WRT_OFF &_BOR40V)


		ORG			0x00
		
		BANKSEL		ANSEL
		CLRF		ANSEL
		CLRF		ANSELH
		
		BANKSEL		TRISA
		MOVLW		0xFF;
		MOVWF		TRISA
		CLRF		TRISB
		MOVLW		b'00011000'
		CLRF		TRISC
		CLRF		TRISD
		CLRF		TRISE
		MOVLW		0x00
		MOVWF		SSPCON2 
		MOVLW		0x40
		MOVWF		SSPSTAT 
		BANKSEL		PORTA
		MOVLW		0x14
		MOVWF		SSPCON

C_P     NOP
        BANKSEL TRISA
E_BF    BTFSS   SSPSTAT,BF
        GOTO    E_BF
        BANKSEL PORTA
        MOVF    SSPBUF,W
        MOVWF   PORTD
        MOVLW   0xF0        ;Salida de datos PORTB
        MOVWF   SSPBUF
        GOTO    C_P   
		END