		PROCESSOR P16F887
		INCLUDE <P16F887.INC>
		__CONFIG _CONFIG1, (_INTRC_OSC_NOCLKOUT & _WDT_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_OFF & _CPD_OFF & _BOR_OFF & _IESO_OFF & _FCMEN_OFF & _LVP_OFF & _DEBUG_OFF)
		__CONFIG _CONFIG2, (_WRT_OFF &_BOR40V)

DCounter1 EQU 0X0C
DCounter2 EQU 0X0D


		ORG			0x00
		
		BANKSEL		ANSEL
		CLRF		ANSEL
		CLRF		ANSELH
		
		;BANCO 1
		BANKSEL		TRISA
		MOVLW		0x00
		MOVWF		TRISA
		CLRF		TRISB
		MOVLW		b'00010000'
		MOVWF		TRISC
		MOVLW		0xFF
		MOVWF		TRISD
		CLRF		TRISE
		MOVLW		0x00
		MOVWF		SSPCON2
		MOVLW		0xC0
		MOVWF		SSPSTAT 
		;BANCO 0
		BANKSEL		PORTA
		MOVLW		0x10
		MOVWF		SSPCON
        BSF     	PORTA,RA5

C_P     BCF     PORTA, RA5
		MOVF	PORTD,W
        ;MOVLW   0x0F        ;Entrada de datos
        MOVWF   SSPBUF
        BANKSEL TRISA
EBF     BTFSS   SSPSTAT,BF
        GOTO    EBF
        BANKSEL PORTA
        MOVF   SSPBUF,W
		MOVWF	PORTB
        ;MOVWF   XR          ;Salida de datos
        BSF     PORTA,RA5
        CALL    R10MS
        GOTO    C_P
		
R10MS
		MOVLW 0Xfa
		MOVWF DCounter1
		MOVLW 0X0d
		MOVWF DCounter2
LOOP
		DECFSZ DCounter1, 1
		GOTO LOOP
		DECFSZ DCounter2, 1
		GOTO LOOP
		RETURN	
		END
